# User config
author: "Shirley Xiao"
tagline: "Shirley Xiao"
description: "Hi, I'm"
keywords: "Shirley, Shirley Xiao, Xiao, Berkeley, Computer Science, CS, Cal, UC Berkeley, UCB, Software, Software Engineer, Software Developer"
email: "stxiao@berkeley.edu"
linkedin: "https://www.linkedin.com/in/s-xiao"
github: "https://github.com/shirleytxiao/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed